"""
    download(
        e5ds :: Union{ERA5Hourly,ERA5Monthly},
        evar :: SingleVariable,
        ereg :: ERA5Region;
        ispy :: Bool = false,
        overwrite :: Bool = false
    ) -> nothing

Downloads ERA5 data from the CDS datastore for a specified Single-Level variable and geographic region.  You can specify to download via python scripts generated by selecting `ispy` to `true`, or to instead use Julia directly.

You must have installed the CDSAPI on your machine and have accepted the terms and conditions on the CDS website in order for this to work.

Arguments
=========

- `e5ds` : The ERA5Dataset specified (Hourly or Monthly)
    - `e5ds.start` defines the start date
    - `e5ds.stop` defines the end date
    - `e5ds.path` defines the path to which all reanalysis data is saved
- `evar` : Specifies the Single-Level variable to be downloaded
- `ereg` : Specifies the `GeoRegion` and the resolution of the data to be downloaded
- `ipsy` : Specifies whether to generate a python script that can be used to download the data instead of Julia
- `overwrite` : `false` by default. If set to true, existing data will be overwritten.
"""
function dkrz(
    e5ds :: ERA5CDStore,
    evar :: ERA5Variable;
    date :: Date,
    domodellevel :: Bool = false
)

    checkdkrzvariable(evar)
    level = checkdkrzlevel(evar,domodellevel)
    tres  = checkdkrztres(e5ds,evar)

    path = "/pool/data/ERA5/E5/$(level)/an/$(tres)/$(@sprintf("%03d",evar.dkrz))"
    if !evar.invariant
        fgrb = "E5$(level)00_$(tres)_$(date)_$(@sprintf("%03d",evar.dkrz)).grb"
    else
        fgrb = "E5$(level)00_$(tres)_2001-01-01_$(@sprintf("%03d",evar.dkrz)).grb"
    end

    return GRIBDataset(joinpath(path,fgrb))

end

checkdkrzvariable(evar::ERA5Variable) = ismissing(evar.dkrz) ? error("$(modulelog()) - This ERA5Variable is unfortunately not provided by the DKRZ servers.") : nothing

checkdkrzlevel(::SingleVariable,:: Bool) = "sf"
checkdkrzlevel(::PressureVariable,domodellevel:: Bool) = domodellevel ? "ml" : "pl"

checkdkrztres(::ERA5Hourly,::PressureVariable)  = "1H"
checkdkrztres(::ERA5Daily,::PressureVariable)   = "1D"
checkdkrztres(::ERA5Monthly,::PressureVariable) = "1M"

checkdkrztres(::ERA5Hourly,evar::SingleVariable)  = evar.invariant ? "IV" : "1H"
checkdkrztres(::ERA5Daily,evar::SingleVariable)   = evar.invariant ? "IV" : "1D"
checkdkrztres(::ERA5Monthly,evar::SingleVariable) = evar.invariant ? "IV" : "1M"

function nativelonlat()

    fname = joinpath(eradir,"dkrzlonlat.txt")
    data = readdlm(fname,',')[:,:]; nlon = Int.(data[:,1]); lat = data[:,2]
    npnt = sum(nlon); nrow = length(lat)
    elon = zeros(npnt)
    elat = zeros(npnt)

    ibeg = Int(0)
    iend = Int(0)
    for irow = 1 : nrow
        ilon  = nlon[irow]
        ibeg  = iend + 1
        iend += ilon
        elon[ibeg:iend] = (0:(ilon-1)) * 360 / ilon
        elat[ibeg:iend] .= lat[irow]
    end

    return elon,elat

end

function closestnativelonlat(
    pnt :: Point2
)

    elon,elat = nativelonlat()
    ex = cosd.(elon) .* cosd.(elat)
    ey = sind.(elon) .* cosd.(elat)
    ez = sind.(elat)

    plon,plat = pnt[1],pnt[2]
    px = cosd.(plon) * cosd.(plat)
    py = sind.(plon) * cosd.(plat)
    pz = sind.(plat)

    return argmin(abs.((ex.-px).^2 .+ (ey.-py).^2 .+ (ez.-pz).^2))

end

function closestnativelonlat(
    pnts :: Vector{Point2}
)

    elon,elat = nativelonlat()
    ex = cosd.(elon) .* cosd.(elat)
    ey = sind.(elon) .* cosd.(elat)
    ez = sind.(elat)

    npnts = length(pnts)
    iarg  = zeros(Int,npnts)
    for ii in 1 : npnts
        ipnt = pnts[ii]
        plon,plat = ipnt[1],ipnt[2]
        px = cosd.(plon) * cosd.(plat)
        py = sind.(plon) * cosd.(plat)
        pz = sind.(plat)
        iarg[ipnt] = argmin(abs.((ex.-px).^2 .+ (ey.-py).^2 .+ (ez.-pz).^2))
    end

    return iarg

end